#!/bin/bash

BRANCH=$1


if [ -f $BRANCH ]
then
    echo ""
    echo "No branch found in the argument."
    echo "usage: git_push <branch>"
    echo ""
else
    echo ""
    read -p "Push to origin (github) (y/n)? " answer
    case $answer in
    [Yy]* )
        git push origin $BRANCH
    ;;
    * )
        echo "Push canceled for origin branch: $BRANCH"
    esac

    echo ""
    read -p "Push to internal (internal) (y/n)? " answer
    case $answer in
    [Yy]* )
        git push internal $BRANCH
    ;;
    * )
        echo "Push canceled for internal branch: $BRANCH"
    esac
fi
